// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var $, $async, CND, PATH, PD, assign, badge, collapse_text, copy, debug, echo, has_full_signatures, help, info, jr, rpr, select, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERCOURSE/MAIN';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PATH = require('path');

  PD = require('pipedreams');

  ({$, $async, select} = PD);

  ({assign, jr} = CND);

  copy = function(x) {
    return assign({}, x);
  };

  //-----------------------------------------------------------------------------------------------------------
  collapse_text = function(list_of_texts) {
    var R;
    R = list_of_texts;
    R = R.join('\n');
    R = R.replace(/^\s*/, '');
    R = R.replace(/\s*$/, '');
    if (R.length !== 0) {
      R = R + '\n';
    }
    return R;
  };

  //-----------------------------------------------------------------------------------------------------------
  has_full_signatures = function(entry) {
    var k;
    for (k in entry) {
      if (k.startsWith('(')) {
        return true;
      }
    }
    return false;
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$as_line_datoms = function(S) {
    var line_nr;
    line_nr = 0;
    return $(function(line, send) {
      var d;
      line_nr += +1;
      d = PD.new_event('^line', line, {
        $: {line_nr}
      });
      if ((d.value.match(/^\s*$/)) != null) {
        d.is_blank = true;
      }
      send(d);
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$skip_comments = function(S) {
    return PD.$filter(function(d) {
      return (d.value.match(S.comments)) == null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$add_headers = function(S) {
    var header_plain_re, header_sig_re, ignore_re;
    header_sig_re = /^(?<ictype>\S+)\s+(?<icname>\S+?)(?<signature>\(.*?\))\s*:\s*(?<trailer>.*?)\s*$/;
    header_plain_re = /^(?<ictype>\S+)\s+(?<icname>\S+)\s*:\s*(?<trailer>.*?)\s*$/;
    ignore_re = /^ignore\s*:\s*$/;
    return $((d, send) => {
      var m;
      if (d.is_blank) {
        return send(d);
      }
      if ((d.value.match(/^\s/)) != null) {
        return send(d);
      }
      if ((m = d.value.match(ignore_re)) != null) {
        return send(PD.new_event('^ignore', copy(m.groups), {
          $: d
        }));
      }
      if ((m = d.value.match(header_sig_re)) != null) {
        return send(PD.new_event('^definition', copy(m.groups), {
          $: d
        }));
      }
      if ((m = d.value.match(header_plain_re)) != null) {
        return send(PD.new_event('^definition', copy(m.groups), {
          $: d
        }));
      }
      //.......................................................................................................
      throw new Error(`µ83473 illegal line ${rpr(d)}`);
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$add_regions = function(S) {
    var last, prv_name, within_region;
    within_region = false;
    prv_name = null;
    last = Symbol('last');
    //.........................................................................................................
    return $({last}, (d, send) => {
      //.......................................................................................................
      if (d === last) {
        if (prv_name != null) {
          send(PD.new_event('>' + prv_name));
          prv_name = null;
        }
        return;
      }
      //.......................................................................................................
      if (select(d, '^line')) {
        if (within_region) {
          return send(d);
        }
        if (d.is_blank) {
          return;
        }
        throw new Error(`µ85818 found line outside of any region: ${rpr(d)}`);
      }
      //.......................................................................................................
      if (prv_name != null) {
        send(PD.new_event('>' + prv_name));
        within_region = false;
        prv_name = null;
      }
      //.......................................................................................................
      if (!within_region) {
        d = CND.deep_copy(d);
        prv_name = d.key.slice(1);
        d.key = '<' + prv_name;
        within_region = true;
        send(d);
      }
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$skip_ignored = function(S) {
    var within_ignore;
    within_ignore = false;
    return $((d, send) => {
      if (select(d, '<ignore')) {
        within_ignore = true;
      } else if (select(d, '>ignore')) {
        within_ignore = false;
      } else if (!within_ignore) {
        send(d);
      }
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$reorder_trailers = function(S) {
    var is_oneliner, within_definition;
    within_definition = false;
    is_oneliner = false;
    return $((d, send) => {
      var trailer;
      //.......................................................................................................
      if (select(d, '<definition')) {
        within_definition = true;
        trailer = d.value.trailer;
        delete d.value.trailer;
        if ((trailer != null) && (trailer.length > 0)) {
          is_oneliner = true;
          send(d);
          send(PD.new_event('^line', '  ' + trailer.trim(), {
            $: d
          }));
        } else {
          send(d);
        }
      //.......................................................................................................
      } else if (select(d, '>definition')) {
        is_oneliner = false;
        within_definition = false;
        send(d);
      //.......................................................................................................
      } else if (within_definition && is_oneliner && (!select(d, '>definition')) && !d.is_blank) {
        throw new Error(`µ87872 illegal follow-up after one-liner: ${rpr(d)}`);
      } else {
        //.......................................................................................................
        send(d);
      }
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.get_signature_and_kenning = function(signature = null) {
    var kenning;
    if (signature == null) {
      return [null, 'null'];
    }
    if (!CND.isa_list(signature)) {
      signature = Object.keys(signature);
    }
    signature = signature.slice(0).sort();
    kenning = '(' + (signature.join(',')) + ')';
    return [signature, kenning];
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$compile_definitions = function(S) {
    var this_definition, this_indentation;
    this_definition = null;
    this_indentation = null;
    //.........................................................................................................
    return $((d, send) => {
      var argument, i, kenning, len, location, match, name, ref, signature, text, type;
      //.......................................................................................................
      if (select(d, '<definition')) {
        name = d.value.icname;
        type = d.value.ictype;
        location = d.$;
        signature = null;
        this_definition = {
          name,
          type,
          text: [],
          location,
          kenning: 'null'
        };
        if (d.value.signature != null) {
          signature = [];
          ref = (d.value.signature.replace(/[()]/g, '')).split(',');
          for (i = 0, len = ref.length; i < len; i++) {
            argument = ref[i];
            if (((argument = argument.trim()) != null) && argument.length > 0) {
              signature.push(argument);
            }
          }
          [signature, kenning] = this.get_signature_and_kenning(signature);
          this_definition.signature = signature;
          this_definition.kenning = kenning;
        }
      //.......................................................................................................
      } else if (select(d, '>definition')) {
        this_definition.text = collapse_text(this_definition.text);
        send(PD.new_event('^definition', this_definition, {
          $: this_definition.location
        }));
        this_definition = null;
        this_indentation = null;
      //.......................................................................................................
      } else if (select(d, '^line')) {
        if (d.is_blank) {
          return this_definition.text.push('');
        }
        text = d.value;
        //.....................................................................................................
        if (this_indentation == null) {
          if ((match = text.match(/^\s+/)) == null) {
            throw new Error(`µ88163 unexpected indentation: ${rpr(d)}`);
          }
          this_indentation = match[0];
        } else {
          //.....................................................................................................
          if (!text.startsWith(this_indentation)) {
            throw new Error(`µ90508 unexpected indentation: ${rpr(d)}`);
          }
        }
        //.....................................................................................................
        text = text.slice(this_indentation.length);
        this_definition.text.push(text);
      } else {
        //.......................................................................................................
        throw new Error(`µ92853 unexpected datom: ${rpr(d)}`);
      }
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.$collect = function(S, collector) {
    return $((d, send) => {
      var definition, entry, kenning, lnr, location, name1, signature, text, type;
      if (!select(d, '^definition')) {
        throw new Error(`µ23982 expected a '^definition', got ${rpr(d)}`);
      }
      //.......................................................................................................
      lnr = d.$.line_nr;
      definition = d.value;
      ({type, text, location, kenning, signature} = definition);
      entry = (collector[name1 = definition.name] != null ? collector[name1] : collector[name1] = {type});
      //.......................................................................................................
      if (d.value.type !== entry.type) {
        throw new Error(`µ94432\nexpected type ${rpr(entry.type)}, got\n${rpr(definition.type)}\n(line #${lnr})`);
      }
      //.......................................................................................................
      if (entry[kenning] != null) {
        throw new Error(`µ23983\nname ${definition.name} with kenning ${rpr(kenning)} already defined:\n${rpr(definition)}\n(line #${lnr})`);
      }
      //.......................................................................................................
      /* TAINT must re-implement */
      if ((kenning === 'null') && (has_full_signatures(entry))) {
        debug(entry);
        throw new Error(`µ23983\ncan't overload explicit-signature definition with a null-signature definition:\n${rpr(definition)}\n(line #${lnr})`);
      }
      //.......................................................................................................
      entry[kenning] = {text, location, kenning, type};
      if (signature != null) {
        entry[kenning].signature = signature;
      }
      //.......................................................................................................
      return null;
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.read_definitions = async function(path) {
    return (await this._read_definitions(PD.read_from_file(path)));
  };

  this.read_definitions_from_text = async function(text) {
    return (await this._read_definitions(PD.new_value_source([text])));
  };

  //-----------------------------------------------------------------------------------------------------------
  this._read_definitions = function(source) {
    return new Promise((resolve, reject) => {
      var R, S, pipeline;
      R = {};
      S = {
        comments: /^--/
      };
      pipeline = [];
      pipeline.push(source);
      pipeline.push(PD.$split());
      pipeline.push(this.$as_line_datoms(S));
      pipeline.push(this.$skip_comments(S));
      pipeline.push(this.$add_headers(S));
      pipeline.push(this.$add_regions(S));
      pipeline.push(this.$skip_ignored(S));
      pipeline.push(this.$reorder_trailers(S));
      pipeline.push(this.$compile_definitions(S));
      pipeline.push(this.$collect(S, R));
      pipeline.push(PD.$drain(function() {
        return resolve(R);
      }));
      PD.pull(...pipeline);
      return null;
    });
  };

}).call(this);

//# sourceMappingURL=main.js.map
