// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var CND, IC, badge, debug, echo, help, info, jr, rpr, test, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'INTERCOURSE/TESTS/MAIN';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  test = require('guy-test');

  jr = JSON.stringify;

  IC = require('../..');

  //-----------------------------------------------------------------------------------------------------------
  this["basic 1"] = async function(T, done) {
    var error, i, len, matcher, probe, probes_and_matchers;
    probes_and_matchers = [
      [
        "procedure x:\n  foo bar",
        {
          "x": {
            "arity": {
              "null": {
                "text": "foo bar\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure x:\n  foo bar\n",
        {
          "x": {
            "arity": {
              "null": {
                "text": "foo bar\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure x:\n  foo bar\n\n",
        {
          "x": {
            "arity": {
              "null": {
                "text": "foo bar\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure x:\n  foo bar\n\nprocedure y:\n  foo bar\n\n",
        {
          "x": {
            "arity": {
              "null": {
                "text": "foo bar\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          },
          "y": {
            "arity": {
              "null": {
                "text": "foo bar\n",
                "location": {
                  "line_nr": 4
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ]
    ];
//.........................................................................................................
    for (i = 0, len = probes_and_matchers.length; i < len; i++) {
      [probe, matcher, error] = probes_and_matchers[i];
      await T.perform(probe, matcher, error, function() {
        return new Promise(async function(resolve, reject) {
          var result;
          // try
          result = (await IC.read_definitions_from_text(probe));
          // catch error
          //   return resolve error.message
          // debug '29929', result
          return resolve(result);
        });
      });
    }
    done();
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this["signatures"] = async function(T, done) {
    var error, i, len, matcher, probe, probes_and_matchers;
    probes_and_matchers = [
      [
        "procedure foobar:\n  some text",
        {
          "foobar": {
            "arity": {
              "null": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar():\n  some text",
        {
          "foobar": {
            "arity": {
              "0": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": []
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first ):\n  some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar(first):\n  some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, ):\n  some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar(first,):\n  some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, second ):\n  some text",
        {
          "foobar": {
            "arity": {
              "2": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first",
        "second"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, second, ):\n  some text",
        {
          "foobar": {
            "arity": {
              "2": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first",
        "second"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, second, ): some text\nprocedure foobar( first ): other text\nprocedure foobar(): blah\n",
        {
          "foobar": {
            "arity": {
              "0": {
                "text": "blah\n",
                "location": {
                  "line_nr": 3
                },
                "signature": []
              },
              "1": {
                "text": "other text\n",
                "location": {
                  "line_nr": 2
                },
                "signature": ["first"]
              },
              "2": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first",
        "second"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ]
    ];
//.........................................................................................................
    for (i = 0, len = probes_and_matchers.length; i < len; i++) {
      [probe, matcher, error] = probes_and_matchers[i];
      await T.perform(probe, matcher, error, function() {
        return new Promise(async function(resolve, reject) {
          var result;
          // try
          result = (await IC.read_definitions_from_text(probe));
          // catch error
          //   return resolve error.message
          // debug '29929', result
          return resolve(result);
        });
      });
    }
    done();
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this["oneliners"] = async function(T, done) {
    var error, i, len, matcher, probe, probes_and_matchers;
    probes_and_matchers = [
      [
        // ["procedure foobar:  some text\n  illegal line",null,'illegal follow-up after one-liner']
        "procedure foobar: some text",
        {
          "foobar": {
            "arity": {
              "null": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                }
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar(): some text",
        {
          "foobar": {
            "arity": {
              "0": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": []
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first ): some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar(first): some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, ): some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar(first,): some text",
        {
          "foobar": {
            "arity": {
              "1": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, second ): some text",
        {
          "foobar": {
            "arity": {
              "2": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first",
        "second"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ],
      [
        "procedure foobar( first, second, ): some text",
        {
          "foobar": {
            "arity": {
              "2": {
                "text": "some text\n",
                "location": {
                  "line_nr": 1
                },
                "signature": ["first",
        "second"]
              }
            },
            "type": "procedure"
          }
        },
        null
      ]
    ];
//.........................................................................................................
    for (i = 0, len = probes_and_matchers.length; i < len; i++) {
      [probe, matcher, error] = probes_and_matchers[i];
      await T.perform(probe, matcher, error, function() {
        return new Promise(async function(resolve, reject) {
          var result;
          // try
          result = (await IC.read_definitions_from_text(probe));
          // catch error
          //   return resolve error
          // debug '29929', result
          return resolve(result);
        });
      });
    }
    done();
    return null;
  };

  //-----------------------------------------------------------------------------------------------------------
  this["_parse demo"] = async function(T, done) {
    var PATH, path;
    PATH = require('path');
    path = PATH.join(__dirname, '../../demos/sqlite-demo.icql');
    debug(JSON.stringify((await IC.read_definitions(path)), null, '  '));
    done();
    return null;
  };

  //###########################################################################################################
  if (module.parent == null) {
    test(this);
  }

  // test @[ "basic 1" ]
// test @[ "signatures" ]
// test @[ "oneliners" ]
// test @[ "_parse demo" ]

}).call(this);

//# sourceMappingURL=main.test.js.map
